/**
 * SpaceTraders API
 * SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://api-server-2-0-0-rc-2-vxxwq5xqdq-uc.a.run.app\", } ```
 *
 * The version of the OpenAPI document: 2.0.0-rc.2
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipRequirements } from './shipRequirements';


/**
 * The reactor of the ship. The reactor is responsible for powering the ship\'s systems and weapons.
 */
export interface ShipReactor { 
    symbol: ShipReactor.SymbolEnum;
    name: string;
    description: string;
    /**
     * Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
     */
    condition?: number;
    powerOutput: number;
    requirements: ShipRequirements;
}
export namespace ShipReactor {
    export type SymbolEnum = 'REACTOR_SOLAR_I' | 'REACTOR_FUSION_I' | 'REACTOR_FISSION_I' | 'REACTOR_CHEMICAL_I' | 'REACTOR_ANTIMATTER_I';
    export const SymbolEnum = {
        SolarI: 'REACTOR_SOLAR_I' as SymbolEnum,
        FusionI: 'REACTOR_FUSION_I' as SymbolEnum,
        FissionI: 'REACTOR_FISSION_I' as SymbolEnum,
        ChemicalI: 'REACTOR_CHEMICAL_I' as SymbolEnum,
        AntimatterI: 'REACTOR_ANTIMATTER_I' as SymbolEnum
    };
}


