/**
 * SpaceTraders API
 * SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://api-server-2-0-0-rc-2-vxxwq5xqdq-uc.a.run.app\", } ```
 *
 * The version of the OpenAPI document: 2.0.0-rc.2
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipRequirements } from './shipRequirements';


/**
 * The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
 */
export interface ShipFrame { 
    symbol: ShipFrame.SymbolEnum;
    name: string;
    description: string;
    /**
     * Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
     */
    condition?: number;
    moduleSlots: number;
    mountingPoints: number;
    fuelCapacity: number;
    requirements: ShipRequirements;
}
export namespace ShipFrame {
    export type SymbolEnum = 'FRAME_PROBE' | 'FRAME_DRONE' | 'FRAME_INTERCEPTOR' | 'FRAME_RACER' | 'FRAME_FIGHTER' | 'FRAME_FRIGATE' | 'FRAME_SHUTTLE' | 'FRAME_EXPLORER' | 'FRAME_MINER' | 'FRAME_LIGHT_FREIGHTER' | 'FRAME_HEAVY_FREIGHTER' | 'FRAME_TRANSPORT' | 'FRAME_DESTROYER' | 'FRAME_CRUISER' | 'FRAME_CARRIER';
    export const SymbolEnum = {
        Probe: 'FRAME_PROBE' as SymbolEnum,
        Drone: 'FRAME_DRONE' as SymbolEnum,
        Interceptor: 'FRAME_INTERCEPTOR' as SymbolEnum,
        Racer: 'FRAME_RACER' as SymbolEnum,
        Fighter: 'FRAME_FIGHTER' as SymbolEnum,
        Frigate: 'FRAME_FRIGATE' as SymbolEnum,
        Shuttle: 'FRAME_SHUTTLE' as SymbolEnum,
        Explorer: 'FRAME_EXPLORER' as SymbolEnum,
        Miner: 'FRAME_MINER' as SymbolEnum,
        LightFreighter: 'FRAME_LIGHT_FREIGHTER' as SymbolEnum,
        HeavyFreighter: 'FRAME_HEAVY_FREIGHTER' as SymbolEnum,
        Transport: 'FRAME_TRANSPORT' as SymbolEnum,
        Destroyer: 'FRAME_DESTROYER' as SymbolEnum,
        Cruiser: 'FRAME_CRUISER' as SymbolEnum,
        Carrier: 'FRAME_CARRIER' as SymbolEnum
    };
}


