/**
 * SpaceTraders API
 * SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://api-server-2-0-0-rc-2-vxxwq5xqdq-uc.a.run.app\", } ```
 *
 * The version of the OpenAPI document: 2.0.0-rc.2
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MarketTradeGood { 
    /**
     * The symbol of the trade good.
     */
    symbol: string;
    /**
     * The typical volume flowing through the market for this type of good. The larger the trade volume, the more stable prices will be.
     */
    tradeVolume: number;
    /**
     * A rough estimate of the total supply of this good in the marketplace.
     */
    supply: MarketTradeGood.SupplyEnum;
    /**
     * The price at which this good can be purchased from the market.
     */
    purchasePrice: number;
    /**
     * The price at which this good can be sold to the market.
     */
    sellPrice: number;
}
export namespace MarketTradeGood {
    export type SupplyEnum = 'SCARCE' | 'LIMITED' | 'MODERATE' | 'ABUNDANT';
    export const SupplyEnum = {
        Scarce: 'SCARCE' as SupplyEnum,
        Limited: 'LIMITED' as SupplyEnum,
        Moderate: 'MODERATE' as SupplyEnum,
        Abundant: 'ABUNDANT' as SupplyEnum
    };
}


