/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://v2.api.spacetraders.io\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type ShipType = 'SHIP_PROBE' | 'SHIP_MINING_DRONE' | 'SHIP_INTERCEPTOR' | 'SHIP_LIGHT_HAULER' | 'SHIP_COMMAND_FRIGATE' | 'SHIP_EXPLORER' | 'SHIP_HEAVY_FREIGHTER' | 'SHIP_LIGHT_SHUTTLE' | 'SHIP_ORE_HOUND' | 'SHIP_REFINING_FREIGHTER';

export const ShipType = {
    Probe: 'SHIP_PROBE' as ShipType,
    MiningDrone: 'SHIP_MINING_DRONE' as ShipType,
    Interceptor: 'SHIP_INTERCEPTOR' as ShipType,
    LightHauler: 'SHIP_LIGHT_HAULER' as ShipType,
    CommandFrigate: 'SHIP_COMMAND_FRIGATE' as ShipType,
    Explorer: 'SHIP_EXPLORER' as ShipType,
    HeavyFreighter: 'SHIP_HEAVY_FREIGHTER' as ShipType,
    LightShuttle: 'SHIP_LIGHT_SHUTTLE' as ShipType,
    OreHound: 'SHIP_ORE_HOUND' as ShipType,
    RefiningFreighter: 'SHIP_REFINING_FREIGHTER' as ShipType
};

