/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipRequirements } from './shipRequirements';


/**
 * A mount is installed on the exterier of a ship.
 */
export interface ShipMount { 
    symbol: ShipMount.SymbolEnum;
    name: string;
    description?: string;
    strength?: number;
    deposits?: Array<ShipMount.DepositsEnum>;
    requirements: ShipRequirements;
}
export namespace ShipMount {
    export type SymbolEnum = 'MOUNT_GAS_SIPHON_I' | 'MOUNT_GAS_SIPHON_II' | 'MOUNT_GAS_SIPHON_III' | 'MOUNT_SURVEYOR_I' | 'MOUNT_SURVEYOR_II' | 'MOUNT_SURVEYOR_III' | 'MOUNT_SENSOR_ARRAY_I' | 'MOUNT_SENSOR_ARRAY_II' | 'MOUNT_SENSOR_ARRAY_III' | 'MOUNT_MINING_LASER_I' | 'MOUNT_MINING_LASER_II' | 'MOUNT_MINING_LASER_III' | 'MOUNT_LASER_CANNON_I' | 'MOUNT_MISSILE_LAUNCHER_I' | 'MOUNT_TURRET_I';
    export const SymbolEnum = {
        GasSiphonI: 'MOUNT_GAS_SIPHON_I' as SymbolEnum,
        GasSiphonIi: 'MOUNT_GAS_SIPHON_II' as SymbolEnum,
        GasSiphonIii: 'MOUNT_GAS_SIPHON_III' as SymbolEnum,
        SurveyorI: 'MOUNT_SURVEYOR_I' as SymbolEnum,
        SurveyorIi: 'MOUNT_SURVEYOR_II' as SymbolEnum,
        SurveyorIii: 'MOUNT_SURVEYOR_III' as SymbolEnum,
        SensorArrayI: 'MOUNT_SENSOR_ARRAY_I' as SymbolEnum,
        SensorArrayIi: 'MOUNT_SENSOR_ARRAY_II' as SymbolEnum,
        SensorArrayIii: 'MOUNT_SENSOR_ARRAY_III' as SymbolEnum,
        MiningLaserI: 'MOUNT_MINING_LASER_I' as SymbolEnum,
        MiningLaserIi: 'MOUNT_MINING_LASER_II' as SymbolEnum,
        MiningLaserIii: 'MOUNT_MINING_LASER_III' as SymbolEnum,
        LaserCannonI: 'MOUNT_LASER_CANNON_I' as SymbolEnum,
        MissileLauncherI: 'MOUNT_MISSILE_LAUNCHER_I' as SymbolEnum,
        TurretI: 'MOUNT_TURRET_I' as SymbolEnum
    };
    export type DepositsEnum = 'QUARTZ_SAND' | 'SILICON_CRYSTALS' | 'PRECIOUS_STONES' | 'ICE_WATER' | 'AMMONIA_ICE' | 'IRON_ORE' | 'COPPER_ORE' | 'SILVER_ORE' | 'ALUMINUM_ORE' | 'GOLD_ORE' | 'PLATINUM_ORE' | 'DIAMONDS' | 'URANITE_ORE' | 'MERITIUM_ORE';
    export const DepositsEnum = {
        QuartzSand: 'QUARTZ_SAND' as DepositsEnum,
        SiliconCrystals: 'SILICON_CRYSTALS' as DepositsEnum,
        PreciousStones: 'PRECIOUS_STONES' as DepositsEnum,
        IceWater: 'ICE_WATER' as DepositsEnum,
        AmmoniaIce: 'AMMONIA_ICE' as DepositsEnum,
        IronOre: 'IRON_ORE' as DepositsEnum,
        CopperOre: 'COPPER_ORE' as DepositsEnum,
        SilverOre: 'SILVER_ORE' as DepositsEnum,
        AluminumOre: 'ALUMINUM_ORE' as DepositsEnum,
        GoldOre: 'GOLD_ORE' as DepositsEnum,
        PlatinumOre: 'PLATINUM_ORE' as DepositsEnum,
        Diamonds: 'DIAMONDS' as DepositsEnum,
        UraniteOre: 'URANITE_ORE' as DepositsEnum,
        MeritiumOre: 'MERITIUM_ORE' as DepositsEnum
    };
}


