/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://v2.api.spacetraders.io\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SurveyDeposit } from './surveyDeposit';


/**
 * A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
 */
export interface Survey { 
    /**
     * A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.
     */
    signature: string;
    /**
     * The symbol of the waypoint that this survey is for.
     */
    symbol: string;
    /**
     * A list of deposits that can be found at this location.
     */
    deposits: Array<SurveyDeposit>;
    /**
     * The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.
     */
    expiration: string;
    /**
     * The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
     */
    size: Survey.SizeEnum;
}
export namespace Survey {
    export type SizeEnum = 'SMALL' | 'MODERATE' | 'LARGE';
    export const SizeEnum = {
        Small: 'SMALL' as SizeEnum,
        Moderate: 'MODERATE' as SizeEnum,
        Large: 'LARGE' as SizeEnum
    };
}


