/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://v2.api.spacetraders.io\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of waypoint.
 */
export type SystemType = 'NEUTRON_STAR' | 'RED_STAR' | 'ORANGE_STAR' | 'BLUE_STAR' | 'YOUNG_STAR' | 'WHITE_DWARF' | 'BLACK_HOLE' | 'HYPERGIANT' | 'NEBULA' | 'UNSTABLE';

export const SystemType = {
    NeutronStar: 'NEUTRON_STAR' as SystemType,
    RedStar: 'RED_STAR' as SystemType,
    OrangeStar: 'ORANGE_STAR' as SystemType,
    BlueStar: 'BLUE_STAR' as SystemType,
    YoungStar: 'YOUNG_STAR' as SystemType,
    WhiteDwarf: 'WHITE_DWARF' as SystemType,
    BlackHole: 'BLACK_HOLE' as SystemType,
    Hypergiant: 'HYPERGIANT' as SystemType,
    Nebula: 'NEBULA' as SystemType,
    Unstable: 'UNSTABLE' as SystemType
};

