/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WaypointTrait { 
    /**
     * The unique identifier of the trait.
     */
    symbol: WaypointTrait.SymbolEnum;
    /**
     * The name of the trait.
     */
    name: string;
    /**
     * A description of the trait.
     */
    description: string;
}
export namespace WaypointTrait {
    export type SymbolEnum = 'UNCHARTED' | 'MARKETPLACE' | 'SHIPYARD' | 'OUTPOST' | 'SCATTERED_SETTLEMENTS' | 'SPRAWLING_CITIES' | 'MEGA_STRUCTURES' | 'OVERCROWDED' | 'HIGH_TECH' | 'CORRUPT' | 'BUREAUCRATIC' | 'TRADING_HUB' | 'INDUSTRIAL' | 'BLACK_MARKET' | 'RESEARCH_FACILITY' | 'MILITARY_BASE' | 'SURVEILLANCE_OUTPOST' | 'EXPLORATION_OUTPOST' | 'MINERAL_DEPOSITS' | 'COMMON_METAL_DEPOSITS' | 'PRECIOUS_METAL_DEPOSITS' | 'RARE_METAL_DEPOSITS' | 'METHANE_POOLS' | 'ICE_CRYSTALS' | 'EXPLOSIVE_GASES' | 'STRONG_MAGNETOSPHERE' | 'VIBRANT_AURORAS' | 'SALT_FLATS' | 'CANYONS' | 'PERPETUAL_DAYLIGHT' | 'PERPETUAL_OVERCAST' | 'DRY_SEABEDS' | 'MAGMA_SEAS' | 'SUPERVOLCANOES' | 'ASH_CLOUDS' | 'VAST_RUINS' | 'MUTATED_FLORA' | 'TERRAFORMED' | 'EXTREME_TEMPERATURES' | 'EXTREME_PRESSURE' | 'DIVERSE_LIFE' | 'SCARCE_LIFE' | 'FOSSILS' | 'WEAK_GRAVITY' | 'STRONG_GRAVITY' | 'CRUSHING_GRAVITY' | 'TOXIC_ATMOSPHERE' | 'CORROSIVE_ATMOSPHERE' | 'BREATHABLE_ATMOSPHERE' | 'JOVIAN' | 'ROCKY' | 'VOLCANIC' | 'FROZEN' | 'SWAMP' | 'BARREN' | 'TEMPERATE' | 'JUNGLE' | 'OCEAN' | 'STRIPPED';
    export const SymbolEnum = {
        Uncharted: 'UNCHARTED' as SymbolEnum,
        Marketplace: 'MARKETPLACE' as SymbolEnum,
        Shipyard: 'SHIPYARD' as SymbolEnum,
        Outpost: 'OUTPOST' as SymbolEnum,
        ScatteredSettlements: 'SCATTERED_SETTLEMENTS' as SymbolEnum,
        SprawlingCities: 'SPRAWLING_CITIES' as SymbolEnum,
        MegaStructures: 'MEGA_STRUCTURES' as SymbolEnum,
        Overcrowded: 'OVERCROWDED' as SymbolEnum,
        HighTech: 'HIGH_TECH' as SymbolEnum,
        Corrupt: 'CORRUPT' as SymbolEnum,
        Bureaucratic: 'BUREAUCRATIC' as SymbolEnum,
        TradingHub: 'TRADING_HUB' as SymbolEnum,
        Industrial: 'INDUSTRIAL' as SymbolEnum,
        BlackMarket: 'BLACK_MARKET' as SymbolEnum,
        ResearchFacility: 'RESEARCH_FACILITY' as SymbolEnum,
        MilitaryBase: 'MILITARY_BASE' as SymbolEnum,
        SurveillanceOutpost: 'SURVEILLANCE_OUTPOST' as SymbolEnum,
        ExplorationOutpost: 'EXPLORATION_OUTPOST' as SymbolEnum,
        MineralDeposits: 'MINERAL_DEPOSITS' as SymbolEnum,
        CommonMetalDeposits: 'COMMON_METAL_DEPOSITS' as SymbolEnum,
        PreciousMetalDeposits: 'PRECIOUS_METAL_DEPOSITS' as SymbolEnum,
        RareMetalDeposits: 'RARE_METAL_DEPOSITS' as SymbolEnum,
        MethanePools: 'METHANE_POOLS' as SymbolEnum,
        IceCrystals: 'ICE_CRYSTALS' as SymbolEnum,
        ExplosiveGases: 'EXPLOSIVE_GASES' as SymbolEnum,
        StrongMagnetosphere: 'STRONG_MAGNETOSPHERE' as SymbolEnum,
        VibrantAuroras: 'VIBRANT_AURORAS' as SymbolEnum,
        SaltFlats: 'SALT_FLATS' as SymbolEnum,
        Canyons: 'CANYONS' as SymbolEnum,
        PerpetualDaylight: 'PERPETUAL_DAYLIGHT' as SymbolEnum,
        PerpetualOvercast: 'PERPETUAL_OVERCAST' as SymbolEnum,
        DrySeabeds: 'DRY_SEABEDS' as SymbolEnum,
        MagmaSeas: 'MAGMA_SEAS' as SymbolEnum,
        Supervolcanoes: 'SUPERVOLCANOES' as SymbolEnum,
        AshClouds: 'ASH_CLOUDS' as SymbolEnum,
        VastRuins: 'VAST_RUINS' as SymbolEnum,
        MutatedFlora: 'MUTATED_FLORA' as SymbolEnum,
        Terraformed: 'TERRAFORMED' as SymbolEnum,
        ExtremeTemperatures: 'EXTREME_TEMPERATURES' as SymbolEnum,
        ExtremePressure: 'EXTREME_PRESSURE' as SymbolEnum,
        DiverseLife: 'DIVERSE_LIFE' as SymbolEnum,
        ScarceLife: 'SCARCE_LIFE' as SymbolEnum,
        Fossils: 'FOSSILS' as SymbolEnum,
        WeakGravity: 'WEAK_GRAVITY' as SymbolEnum,
        StrongGravity: 'STRONG_GRAVITY' as SymbolEnum,
        CrushingGravity: 'CRUSHING_GRAVITY' as SymbolEnum,
        ToxicAtmosphere: 'TOXIC_ATMOSPHERE' as SymbolEnum,
        CorrosiveAtmosphere: 'CORROSIVE_ATMOSPHERE' as SymbolEnum,
        BreathableAtmosphere: 'BREATHABLE_ATMOSPHERE' as SymbolEnum,
        Jovian: 'JOVIAN' as SymbolEnum,
        Rocky: 'ROCKY' as SymbolEnum,
        Volcanic: 'VOLCANIC' as SymbolEnum,
        Frozen: 'FROZEN' as SymbolEnum,
        Swamp: 'SWAMP' as SymbolEnum,
        Barren: 'BARREN' as SymbolEnum,
        Temperate: 'TEMPERATE' as SymbolEnum,
        Jungle: 'JUNGLE' as SymbolEnum,
        Ocean: 'OCEAN' as SymbolEnum,
        Stripped: 'STRIPPED' as SymbolEnum
    };
}


